### PR TITLE
Update theme.css

### PR DESCRIPTION
**Pull request by tobealive**
Hello friend, thanks for your creation! It's my favorite theme I have to admit. But it came with some small errors, unfortunately.

This commit fixes jumpiness while resizing, spacing errors, broken pinned windows, full-screen graph view and includes some other small fixes and improvements which let the user enjoy this theme even more.

### CODE REVIEW

**Comment by Crowds21** [comment]
Thanks for your commit!
I have pushed v2.0.1 to the bazaar.

**Comment by tobealive** [comment]
❤️🙏

**Comment by tobealive** [comment]
While working with the app and the theme today I realized some more nuances that could be improved. So I decided to update my fork. 

The fixes:
- The Graph View Layers level was still conflicting with the Backlinks Layer. 
- Another little fix on the Backlinks panel.

I would like to run a formatter over the file but then the whole file is displayed as changed. With all the red the changes can't be recognized that well. So I avoided using one. Also, I want to say sorry for not commenting exactly what that CSS I'm changing and is doing. Just hoping it's okay with those simple changes. When is okay with you I'll create another pull request.

**Comment by Crowds21** [comment]
@tobealive 
I'm busy these days. I'm sorry I didn't reply to you yesterday
It doesn't matter. But don't delete the comments.
After all, this is just a CSS file, not a part of a huge project. And it doesn't take long to read the code. Just do it.
Thank you for your commit.

**Comment by tobealive** [comment]
Hey, nice to read from you :) no worries about the time!
Yes, the comments in the code are untouched. 
I worked this day again with SiYuan and the theme. Nothing wrong with it has appeared to me. 
I'll make the pull request :).

**Pull request merged**
